#!/bin/bash

# OpenTalk Wisp - Production Deployment Script
# This script helps you deploy the application to production

set -e

echo "🚀 OpenTalk Wisp - Production Deployment"
echo "=========================================="
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if .env exists
if [ ! -f .env ]; then
    echo -e "${YELLOW}Warning: .env file not found${NC}"
    echo "Creating .env from .env.example..."
    cp .env.example .env
    echo -e "${RED}Please edit .env with your production values before continuing!${NC}"
    exit 1
fi

# Function to generate random string
generate_secret() {
    node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
}

# Check if JWT_SECRET is set
source .env
if [ -z "$JWT_SECRET" ] || [ "$JWT_SECRET" = "your-jwt-secret-minimum-32-characters-random-string" ]; then
    echo -e "${YELLOW}Generating new JWT_SECRET...${NC}"
    NEW_SECRET=$(generate_secret)
    sed -i "s/JWT_SECRET=.*/JWT_SECRET=$NEW_SECRET/" .env
    echo -e "${GREEN}✓ JWT_SECRET generated${NC}"
fi

echo ""
echo "Select deployment method:"
echo "1) Docker Compose (Local or VPS)"
echo "2) Railway (Cloud PaaS)"
echo "3) VPS Manual Setup"
echo "4) Build for production (manual deploy)"
echo ""
read -p "Enter choice [1-4]: " choice

case $choice in
    1)
        echo ""
        echo "🐳 Deploying with Docker Compose..."
        echo ""
        
        # Check if Docker is installed
        if ! command -v docker &> /dev/null; then
            echo -e "${RED}Docker is not installed. Please install Docker first.${NC}"
            exit 1
        fi
        
        # Build and start containers
        echo "Building images..."
        docker-compose build
        
        echo ""
        echo "Starting containers..."
        docker-compose up -d
        
        echo ""
        echo -e "${GREEN}✓ Deployment complete!${NC}"
        echo ""
        echo "Your application is running at:"
        echo "  Frontend: http://localhost:3000"
        echo "  Backend:  http://localhost:3001"
        echo "  Swagger:  http://localhost:3001/api"
        echo ""
        echo "View logs with: docker-compose logs -f"
        echo "Stop with: docker-compose down"
        ;;
        
    2)
        echo ""
        echo "☁️  Railway Deployment Guide"
        echo ""
        echo "1. Push your code to GitHub:"
        echo "   git add ."
        echo "   git commit -m 'feat: prepare for production'"
        echo "   git push origin main"
        echo ""
        echo "2. Go to https://railway.app and:"
        echo "   - Sign up with GitHub"
        echo "   - Create new project from your repo"
        echo "   - Add PostgreSQL database"
        echo "   - Configure environment variables"
        echo ""
        echo "3. See QUICK_START_PRODUCTION.md for detailed instructions"
        echo ""
        echo "Environment variables needed:"
        echo "  Backend:"
        echo "    DATABASE_URL (auto-generated by Railway)"
        echo "    JWT_SECRET=$JWT_SECRET"
        echo "    NODE_ENV=production"
        echo "    PORT=3001"
        echo ""
        echo "  Frontend:"
        echo "    NEXT_PUBLIC_API_URL=https://your-backend.railway.app"
        echo ""
        ;;
        
    3)
        echo ""
        echo "🖥️  VPS Manual Setup Guide"
        echo ""
        echo "Follow these steps on your VPS:"
        echo ""
        echo "1. Install dependencies:"
        echo "   curl -fsSL https://deb.nodesource.com/setup_20.x | bash -"
        echo "   apt install -y nodejs postgresql nginx"
        echo "   npm install -g pnpm pm2"
        echo ""
        echo "2. Clone repository:"
        echo "   cd /var/www"
        echo "   git clone YOUR_REPO_URL opentalk-wisp"
        echo "   cd opentalk-wisp"
        echo "   pnpm install"
        echo ""
        echo "3. Configure environment variables (copy .env to server)"
        echo ""
        echo "4. Setup database:"
        echo "   sudo -u postgres psql"
        echo "   CREATE DATABASE opentalk_wisp;"
        echo "   CREATE USER opentalk WITH PASSWORD 'YOUR_PASSWORD';"
        echo "   GRANT ALL PRIVILEGES ON DATABASE opentalk_wisp TO opentalk;"
        echo ""
        echo "5. Build and start:"
        echo "   cd apps/backend"
        echo "   pnpm prisma generate"
        echo "   pnpm prisma migrate deploy"
        echo "   pnpm build"
        echo ""
        echo "   cd ../frontend"
        echo "   pnpm build"
        echo ""
        echo "   cd ../.."
        echo "   pm2 start ecosystem.config.js"
        echo "   pm2 save"
        echo "   pm2 startup"
        echo ""
        echo "See DEPLOYMENT.md for complete VPS setup guide"
        echo ""
        ;;
        
    4)
        echo ""
        echo "🔨 Building for production..."
        echo ""
        
        # Install dependencies
        echo "Installing dependencies..."
        pnpm install
        
        # Backend build
        echo ""
        echo "Building backend..."
        cd apps/backend
        pnpm prisma generate
        pnpm build
        cd ../..
        
        # Frontend build
        echo ""
        echo "Building frontend..."
        cd apps/frontend
        pnpm build
        cd ../..
        
        echo ""
        echo -e "${GREEN}✓ Build complete!${NC}"
        echo ""
        echo "Built files:"
        echo "  Backend:  apps/backend/dist/"
        echo "  Frontend: apps/frontend/.next/"
        echo ""
        echo "To run in production:"
        echo "  Backend:  cd apps/backend && pnpm start:prod"
        echo "  Frontend: cd apps/frontend && pnpm start"
        echo ""
        ;;
        
    *)
        echo -e "${RED}Invalid choice${NC}"
        exit 1
        ;;
esac

echo ""
echo "📚 Additional resources:"
echo "  - DEPLOYMENT.md - Complete deployment guide"
echo "  - QUICK_START_PRODUCTION.md - Railway quick start"
echo "  - UI_IMPROVEMENTS.md - UI/UX improvement plan"
echo ""
