#!/bin/bash

echo "🚂 Railway Environment Variables Setup Helper"
echo "=============================================="
echo ""
echo "Copy and paste these variables in Railway Dashboard:"
echo ""
echo "📍 Go to: Railway → opentalk-wisp-backend → Variables"
echo ""
echo "---------------------------------------------------"
echo "# DATABASE (Reference Variable)"
echo "---------------------------------------------------"
echo "DATABASE_URL=\${{Postgres.DATABASE_URL}}"
echo ""
echo "---------------------------------------------------"
echo "# REDIS (Reference Variables)"
echo "---------------------------------------------------"
echo "REDIS_URL=\${{Redis.REDIS_URL}}"
echo "REDIS_HOST=\${{Redis.REDIS_HOST}}"
echo "REDIS_PORT=\${{Redis.REDIS_PORT}}"
echo ""
echo "---------------------------------------------------"
echo "# JWT Configuration"
echo "---------------------------------------------------"
echo "JWT_SECRET=$(openssl rand -base64 32)"
echo "JWT_EXPIRES_IN=7d"
echo ""
echo "---------------------------------------------------"
echo "# Application"
echo "---------------------------------------------------"
echo "NODE_ENV=production"
echo ""
echo "---------------------------------------------------"
echo "# Optional: OpenAI (for AI features)"
echo "---------------------------------------------------"
echo "# OPENAI_API_KEY=sk-your-key-here"
echo ""
echo "=============================================="
echo ""
echo "⚠️  IMPORTANT STEPS:"
echo "1. Add DATABASE_URL as a 'Variable Reference' pointing to Postgres"
echo "2. Add REDIS_URL, REDIS_HOST, REDIS_PORT as 'Variable References' pointing to Redis"
echo "3. Copy the JWT_SECRET generated above (it's random and secure)"
echo "4. Save all variables"
echo ""
echo "📦 VOLUME SETUP:"
echo "1. Go to: Settings → Volumes"
echo "2. Click: + New Volume"
echo "3. Mount Path: /app/wa-sessions"
echo "4. Size: 1 GB"
echo ""
